"""Schema definitions for Baseball Savant data structures."""

from collections.abc import Mapping
from typing import Final

import polars as pl

SAVANT_PARK_FACTORS_REQUIRED: Final[tuple[str, ...]] = (
    "venue_id",
    "venue_name",
    "year",
)

SAVANT_PARK_FACTORS_TYPES: Final[dict[str, pl.DataType | type[pl.DataType]]] = {
    "venue_id": pl.Int64,
    "venue_name": pl.String,
    "team_id": pl.Int64,
    "team_name": pl.String,
    "year": pl.Int64,
    "year_range": pl.String,
    "bat_side": pl.String,
    "n_pa": pl.Int64,
    "park_factor": pl.Int64,
    "woba_factor": pl.Int64,
    "runs_factor": pl.Int64,
    "hr_factor": pl.Int64,
    "hits_factor": pl.Int64,
    "singles_factor": pl.Int64,
    "doubles_factor": pl.Int64,
    "triples_factor": pl.Int64,
    "so_factor": pl.Int64,
    "bb_factor": pl.Int64,
    "hard_hit_factor": pl.Int64,
}

SAVANT_SCHEMA_OVERRIDES: Final[Mapping[str, pl.DataType | type[pl.DataType]]] = {
    "pitcher": pl.Int64,
    "batter": pl.Int64,
    "player_id": pl.Int64,
    "year": pl.Int64,
    "release_speed": pl.Float64,
    "zone": pl.Int64,
    "balls": pl.Int64,
    "strikes": pl.Int64,
    "game_year": pl.Int64,
    "outs_when_up": pl.Int64,
    "inning": pl.Int64,
    "launch_speed": pl.Float64,
    "launch_angle": pl.Float64,
    "game_pk": pl.Int64,
    "bat_speed": pl.Float64,
    "swing_length": pl.Float64,
    "miss_distance": pl.Float64,
    "effective_speed": pl.Float64,
    "release_spin_rate": pl.Float64,
    "release_extension": pl.Float64,
    "release_pos_x": pl.Float64,
    "release_pos_y": pl.Float64,
    "release_pos_z": pl.Float64,
    "pfx_x": pl.Float64,
    "pfx_z": pl.Float64,
    "plate_x": pl.Float64,
    "plate_z": pl.Float64,
    "hc_x": pl.Float64,
    "hc_y": pl.Float64,
    "vx0": pl.Float64,
    "vy0": pl.Float64,
    "vz0": pl.Float64,
    "ax": pl.Float64,
    "ay": pl.Float64,
    "az": pl.Float64,
    "sz_top": pl.Float64,
    "sz_bot": pl.Float64,
    "hit_distance_sc": pl.Float64,
    "estimated_ba_using_speedangle": pl.Float64,
    "estimated_woba_using_speedangle": pl.Float64,
    "woba_value": pl.Float64,
    "woba_denom": pl.Float64,
    "babip_value": pl.Float64,
    "iso_value": pl.Float64,
    "spin_axis": pl.Float64,
    "pitch_number": pl.Int64,
    "at_bat_number": pl.Int64,
}
