blank_issues_enabled: false
contact_links:
  - name: "💬 Ask a Question / Discussion"
    url: https://github.com/nicko4o/polars-baseball/discussions
    about: Please ask questions, share ideas, or showcase your work here instead of opening issues.
