from __future__ import annotations

from collections.abc import Sequence

import polars as pl

from polars_baseball._config import FG_MAX_RESULTS
from polars_baseball.apis.fangraphs import (
    FanGraphsFilter,
    FanGraphsFilterInput,
    FanGraphsRequest,
    fg_data,
)
from polars_baseball.context import BaseballContext
from polars_baseball.enums.fangraphs import (
    FangraphsLeague,
    FangraphsMonth,
    FangraphsPositions,
    FangraphsStatColumn,
    FangraphsStatsCategory,
)


async def _run_fg(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
    category: FangraphsStatsCategory,
    is_team_data: bool = False,
) -> pl.DataFrame:
    request = FanGraphsRequest.from_raw(
        start_season=start_season,
        end_season=end_season,
        stats_category=category,
        is_team_data=is_team_data,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
    )
    return await fg_data(request, context=context)


async def batting(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    filters: list[FanGraphsFilter] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs batting leaderboard data for individual players."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.BATTING,
    )


async def pitching(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs pitching leaderboard data for individual players."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.PITCHING,
        is_team_data=False,
    )


async def fielding(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs fielding leaderboard data for individual players."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.FIELDING,
        is_team_data=False,
    )


async def team_batting(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs team batting leaderboard data."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.BATTING,
        is_team_data=True,
    )


async def team_pitching(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs team pitching leaderboard data."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.PITCHING,
        is_team_data=True,
    )


async def team_fielding(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs team fielding leaderboard data."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.FIELDING,
        is_team_data=True,
    )


async def team_starters(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs team starting pitcher leaderboard data."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.STARTERS,
        is_team_data=True,
    )


async def team_relievers(
    start_season: int,
    *,
    end_season: int | None = None,
    league: str | FangraphsLeague = FangraphsLeague.ALL,
    month: str | FangraphsMonth = FangraphsMonth.ALL,
    position: str | FangraphsPositions = FangraphsPositions.ALL,
    stat_columns: str | list[str] | list[FangraphsStatColumn] = "ALL",
    qual: int | None = None,
    split_seasons: bool = True,
    on_active_roster: bool = False,
    minimum_age: int = 0,
    maximum_age: int = 100,
    team: str = "",
    filters: Sequence[FanGraphsFilterInput] | None = None,
    players: str = "",
    max_results: int = FG_MAX_RESULTS,
    context: BaseballContext | None = None,
) -> pl.DataFrame:
    """Fetch FanGraphs team relief pitcher leaderboard data."""
    return await _run_fg(
        start_season=start_season,
        end_season=end_season,
        league=league,
        month=month,
        position=position,
        stat_columns=stat_columns,
        qual=qual,
        split_seasons=split_seasons,
        on_active_roster=on_active_roster,
        minimum_age=minimum_age,
        maximum_age=maximum_age,
        team=team,
        filters=filters,
        players=players,
        max_results=max_results,
        context=context,
        category=FangraphsStatsCategory.RELIEVERS,
        is_team_data=True,
    )


__all__ = [
    "batting",
    "fielding",
    "pitching",
    "team_batting",
    "team_fielding",
    "team_pitching",
    "team_relievers",
    "team_starters",
]
